load("@rules_java//java:java_binary.bzl", "java_binary")
load("@rules_java//java:java_import.bzl", "java_import")
load("@rules_kotlin//kotlin/internal/jvm:jvm.bzl", "kt_jvm_binary")

kt_jvm_binary(
    name = "konanc",
    srcs = [
        "Konanc.kt",
    ],
    main_class = "rules_kotlin_native.KonancKt",
    deps = [
        "//kotlin_native:konanc_libraries",
        "@bazel_worker_java//src/main/java/com/google/devtools/build/lib/worker:work_request_handlers"
    ],
    visibility = ["//visibility:public"],
)

kt_jvm_binary(
    name = "cinterop",
    srcs = [
        "Cinterop.kt",
    ],
    main_class = "rules_kotlin_native.CinteropKt",
    deps = [
        "//kotlin_native:konanc_libraries",
    ],
    visibility = ["//visibility:public"],
)

kt_jvm_binary(
    name = "klib",
    srcs = [
        "Klib.kt",
    ],
    main_class = "rules_kotlin_native.KlibKt",
    deps = [
        "//kotlin_native:konanc_libraries",
    ],
    visibility = ["//visibility:public"],
)

java_binary(
    name = "ksp_compiler",
    srcs = [
        "KspCompiler.java",
    ],
    main_class = "rules_kotlin_native.KspCompiler",
    deps = [
        "@kotlin_native_ksp//:symbol-processing-aa",
        "@kotlin_native_ksp//:symbol-processing-api",
        "@kotlin_native_ksp//:symbol-processing-common-deps",
    ],
    runtime_deps = [
        "@rules_kotlin//kotlin/compiler:kotlin-stdlib",
        ":kotlinx-coroutines-core-jvm",
    ],
    visibility = ["//kotlin_native/internal:__pkg__"],
)

# rules_kotlin exports this but declares it 'neverlink = True'.
java_import(
    name = "kotlinx-coroutines-core-jvm",
    jars = [":kotlinx-coroutines-core-jvm-jar"],
)

filegroup(
    name = "kotlinx-coroutines-core-jvm-jar",
    srcs = ["@rules_kotlin//kotlin/compiler:kotlinx-coroutines-core-jvm"],
)
